version: '2'
services:
  redis:
      image: 'redis:3.0-alpine'
      command: redis-server --requirepass securepassword
      ports:
        - '6379:6379'
  app:
    build: .
    ports:
      - "3000:80"
    links:
      - "redis"